language: go
go:
  - 1.6

env:
  - "MY_GOOS=linux MY_GOARCH=386"
  - "MY_GOOS=darwin MY_GOARCH=386"
  - "MY_GOOS=windows MY_GOARCH=386"
  - "MY_GOOS=linux MY_GOARCH=amd64"
  - "MY_GOOS=darwin MY_GOARCH=amd64"
  - "MY_GOOS=windows MY_GOARCH=amd64"

before_install:
# workaround for travis-ci/gimme#42
  - curl -o go.tar.gz -sL https://storage.googleapis.com/golang/go1.6.3.linux-amd64.tar.gz
  - tar -C $HOME -xf go.tar.gz
  - rm go.tar.gz
  - export GOROOT="${HOME}/go"
  - export PATH="${GOROOT}/bin:${PATH}"
  - export GOOS="${MY_GOOS}"
  - export GOARCH="${MY_GOARCH}"
# end of workaround ###
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover

install:
  - "go get -d -v ./..."

script:
  - "go install -v ./..."
  - "if test $GOOS.$GOARCH = linux.amd64; then ${GOPATH}/bin/gotestcover -v -coverprofile=coverage.report ./...; go tool cover -func=coverage.report; fi"

after_script:
  - "$HOME/gopath/bin/goveralls -coverprofile=coverage.report -service=travis-ci"

before_deploy:
  - "source .travis_rename_releases.sh"

after_script:

  - "$HOME/gopath/bin/goveralls -coverprofile=coverage.report -service=travis-ci"

notifications:
  irc:
    channels:
    - irc.mozilla.org#taskcluster-bots
    on_success: change
    on_failure: always
    template:
    - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
    - 'Change view : %{compare_url}'
    - 'Build details : %{build_url}'
    - 'Commit message : %{commit_message}'

deploy:
  provider: releases
  api_key:
    secure: U47CmXsqbRsb5095urEMEeQJu+HmV0X8PPpD0WQXzFyYTNI06nAx+U2efubrfrfa/fhNpMFDCDZlbtKmgO62ob7UcBsDQ2HxgLBZEmn3TpqKkMYW/o8JTa1a9zi6hEcb9bF6txw9Tpi6iqZbu/sFRBGlKWE6R42tth7pTSIzD9gMKvx1YRAeZKiUlVm2+RquO0FgryxgmIWT2Fr9gg7pVdkNjTpdYIjySPXNg+xgsywSVbFoFaI6oqqO3OHjDrkBNJfrr6SPsNCE95XJ4Bw1JUsOHaTtS+xNn5VXdTpWgsrT1qZy2PxP3VRWB76sNoeChhrG3V6vjcIbVco4dJbcr/iSASG3ORDL5yiCwIWWdBCdEBcIG655sOWkFINRYsVlIvxiNiABRJvGvTUXkxNMhOnMIjgTzPxGLFNzTjvtw0QvIhpHq5N2q4q2pgGNgamZhyIVA4MxTR2RwMEIuCJAr4ref229v9iaHVyt9LrAwrsgW28PUu+BehzaCrYtb3Rp8vqTpDxOCB69fMOjuwQJfzrvyTjKEYjpTKY9RX5KPNI+5Uiltw7Su4qDY91Q4rUrr0A9RE7eTcqVSaA8/wiWvIhGZFL3DR8F8tr1Hjl8RJuDJn14yAldUa2c81RlP5hm2pNZH56+pMdNqpNrRvAaEmKk4mnYdmMa6dVTplCNu0c=
  file:
    - "${RELEASE_FILE}"
  on:
    repo: taskcluster/slugid-go
    tags: true
